AllCops:
  Exclude:
    - test/**/*
    - Gemfile
  TargetRubyVersion: 2.3

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 120

Metrics/ParameterLists:
  Max: 8

MethodLength:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Name:
  Enabled: false

Style/RaiseArgs:
  Enabled: false
